const COURSES = [
  {
    id: 'seagolf-meri',
    name: 'SeaGolf Meri',
    club: 'Sea Golf Rönnäs',
    domain: 'api.seagolf.fi',
    productId: 7,
    golfId: 1,
    closedIfNoRows: true,  // pre-creates slots (status 4 visible)
    lat: 60.3652, lng: 26.0461,
  },
  {
    id: 'seagolf-puisto',
    name: 'SeaGolf Puisto',
    club: 'Sea Golf Rönnäs',
    domain: 'api.seagolf.fi',
    productId: 8,
    golfId: 1,
    closedIfNoRows: false, // only creates rows on booking
    lat: 60.3645, lng: 26.0468,
  },
  {
    id: 'shg-luukki',
    name: 'SHG Luukki',
    club: 'Suur-Helsingin Golf',
    domain: 'api.shg.fi',
    productId: 53,
    golfId: 1,
    resourceId: 1,
    closedIfNoRows: false,
    memberOnlyMinutes: [20, 50],
    lat: 60.3199, lng: 24.6714,
  },
  {
    id: 'shg-lakisto',
    name: 'SHG Lakisto',
    club: 'Suur-Helsingin Golf',
    domain: 'api.shg.fi',
    productId: 53,
    golfId: 1,
    resourceId: 2,
    closedIfNoRows: false,
    memberOnlyMinutes: [20, 50],
    lat: 60.3573, lng: 24.6528,
  },
  {
    id: 'ringside',
    name: 'Ringside Golf',
    club: 'Espoo Ringside Golf',
    domain: 'api.ringsidegolf.fi',
    productId: 17,
    golfId: 1,
    closedIfNoRows: true,  // pre-creates slots (status 4 visible)
    lat: 60.2765, lng: 24.7427,
  },
  {
    id: 'gumbole',
    name: 'Gumböle Golf',
    club: 'Gumböle Golf',
    domain: 'api.espoogolf.fi',
    productId: 29,
    golfId: 1,
    closedIfNoRows: true,  // pre-creates slots (status 4 visible)
    lat: 60.2246, lng: 24.6113,
  },
  {
    id: 'tgk',
    name: 'Tuusulan GK',
    club: 'Tuusulan Golfklubi',
    domain: 'api.tgk.fi',
    productId: 108,
    golfId: 1,
    closedIfNoRows: true,  // pre-creates slots (status 4 visible)
    lat: 60.4160, lng: 25.0508,
  },
  {
    id: 'hirvihaara',
    name: 'Hirvihaara Golf',
    club: 'Hirvihaara Golf Mäntsälä',
    domain: 'api.hirvihaarangolf.fi',
    productId: 7,
    golfId: 1,
    closedIfNoRows: false,
    memberOnlyRules: [
      // Weekends: whole-hour slots 08:00–16:00 are member-only
      { minutes: [0], hours: { from: 8, to: 16 }, weekendOnly: true },
    ],
    lat: 60.6289, lng: 25.2114,
  },
  {
    id: 'hyvigolf',
    name: 'Hyvigolf',
    club: 'Hyvinkään Golf',
    domain: 'api.hyvigolf.fi',
    productId: 413,
    golfId: 1,
    closedIfNoRows: true,  // pre-creates slots (status 4 visible)
    lat: 60.6565, lng: 24.8187,
  },
  {
    id: 'keimola-kirkka',
    name: 'Keimola Kirkka',
    club: 'Keimola Golf',
    domain: 'api.keimolagolf.com',
    productId: 165,
    golfId: 1,
    closedIfNoRows: false,
    lat: 60.3235, lng: 24.8033,
  },
  {
    id: 'keimola-saras',
    name: 'Keimola Saras',
    club: 'Keimola Golf',
    domain: 'api.keimolagolf.com',
    productId: 166,
    golfId: 1,
    closedIfNoRows: false,
    lat: 60.3228, lng: 24.8040,
  },
  {
    id: 'porvoo',
    name: 'Porvoo Golf',
    club: 'Porvoo Golf',
    domain: 'api.porvoogolf.fi',
    productId: 7,
    golfId: 1,
    closedIfNoRows: false,
    lat: 60.4211, lng: 25.6995,
  },
  {
    id: 'nurmi-18r',
    name: 'Nurmijärvi Golf 18r',
    club: 'Nurmijärven Golf',
    domain: 'api.nurmijarvigolf.fi',
    productId: 1523,
    golfId: 1,
    closedIfNoRows: false,
    lat: 60.5008, lng: 24.5737,
  },
  {
    id: 'nurmi-9r',
    name: 'Nurmijärvi Golf 9r',
    club: 'Nurmijärven Golf',
    domain: 'api.nurmijarvigolf.fi',
    productId: 1524,
    golfId: 1,
    closedIfNoRows: false,
    lat: 60.5001, lng: 24.5744,
  },
  {
    id: 'stlg-pyha',
    name: 'Pyhä Lauri 18r',
    club: 'St Laurence Golf',
    domain: 'api.stlg.fi',
    productId: 7,
    golfId: 1,
    closedIfNoRows: false,
    infoTags: [
      { label: 'Caddiemasterilta', minutes: [30, 35] },
      { label: 'Caddiemasterilta', minutes: [0], weekends: true },
      { label: 'Palloränni', upto: { h: 9, m: 5 }, suppressTags: ['Caddiemasterilta'] },
      { label: 'Palloränni', from: { h: 17, m: 1 }, suppressTags: ['Caddiemasterilta'] },
    ],
    lat: 60.2265, lng: 24.0676,
  },
  {
    id: 'stlg-kalkki',
    name: 'Kalkki-Petteri 18r',
    club: 'St Laurence Golf',
    domain: 'api.stlg.fi',
    productId: 8,
    golfId: 1,
    closedIfNoRows: false,
    teeTimeOffset: 5,
    infoTags: [
      { label: 'Caddiemasterilta', minutes: [35] },
      { label: 'Caddiemasterilta', minutes: [5], weekends: true },
      { label: 'Palloränni', upto: { h: 9, m: 5 }, suppressTags: ['Caddiemasterilta'] },
      { label: 'Palloränni', from: { h: 17, m: 1 }, suppressTags: ['Caddiemasterilta'] },
    ],
    lat: 60.2258, lng: 24.0683,
  },
  {
    id: 'ruukki',
    name: 'Ruukkigolf',
    club: 'Ruukkigolf',
    domain: 'api.ruukkigolf.fi',
    productId: 7,
    golfId: 1,
    closedIfNoRows: false,
    lat: 60.1104, lng: 23.4717,
  },
];

module.exports = COURSES;
